/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RpasekAmbulanceWlList {
    }
}
declare global {
    interface HTMLRpasekAmbulanceWlListElement extends Components.RpasekAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLRpasekAmbulanceWlListElement: {
        prototype: HTMLRpasekAmbulanceWlListElement;
        new (): HTMLRpasekAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "rpasek-ambulance-wl-list": HTMLRpasekAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface RpasekAmbulanceWlList {
    }
    interface IntrinsicElements {
        "rpasek-ambulance-wl-list": RpasekAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rpasek-ambulance-wl-list": LocalJSX.IntrinsicElements["rpasek-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLRpasekAmbulanceWlListElement>;
        }
    }
}
